---
script:
  - echo "Running tests... Done! Yay!"
after_success:
  - git config --global user.name "Golem Travisovis"
  - git config --global user.email "rarash@gatech.edu"
  - sudo apt-get install expect
  - mkdir -p $HOME/.ssh
  - echo "StrictHostKeyChecking no" >> $HOME/.ssh/config
  - cp -t $HOME/.ssh id_rsa
  - SSHCMD='git clone git@github.com:Tarrasch/deploy-keys-testing.git'
  - expect -c "spawn $SSHCMD; expect \"passphrase:\"; send \"${SSHPASS}\\n\"; interact"
  - cd deploy-keys-testing
  - echo a >> a && git add a && git commit -m"Wow, edited from travis script!"
  - SSHCMD='git push origin master'
  - expect -c "spawn $SSHCMD; expect \"passphrase:\"; send \"${SSHPASS}\\n\"; interact"
env:
 global:
  secure: "Cio13Xy/eaEQ2aNAoDvmOypgeM4LniYrcdqKpcqOpzzjpvvzKnyyUWlfSe+O\nvdgr+2BniAbUAFFIXyfSE9s+F538OoetGZ57Zdj10qyEpiTzcI1DsfBXnLjy\n9z5nOFseke6yEeVuW91G9GqiVm6pnnUfHSeeMjhdfdr8726N/2M="
